config/routes.rb
   
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/concerns/home_controller.rb
class HomeController <ApplicationController
	def index
	
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @user = User.all
  end

  def show
    @posts = @user.posts
  end

  def edit
  end

  def update
  end

  def destroy
    @user.destroy
    redirect_to_root_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container home-title">
	<div class='row'>
		<div class="col-12">
			<div style="height:50px;"></div>
			<h1 class="home-title-text">Avec Cora, pour Epitech.</h1>
		<div style="height:10px;"></div>
		</div>
		<div class="col-12">
			<%= image_tag "https://res.cloudinary.com/dfefpyzcm/image/upload/v1643818118/kq7n2sj19mzqtgy58bpe.jpg", alt:"intro", class:"img-fluid"%>	
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-12 banner2">
				<p><span class="bold">Soutenez la candidature de Cora :</span> Nous avons besoin de vous ! PS : Tout don est bienvenue (chèque, espèces, virement et cryptomonnaies)</p>
		</div>
	</div>
</div>

<div style="height:70px;"></div>

<div class='container'>
	<div class="row">
		<div class="col-6 col-paral">
			<%= image_tag "https://res.cloudinary.com/dfefpyzcm/image/upload/v1643993326/pexels-andrea-piacquadio-3761509_y1g3um.jpg", alt:"intro", class:"img-fluid img-index-bloc"%>
				<div class="bloc-bleu">
				<%= link_to 'Parrainage', new_post_path, class:'bloc-bleu-text' %>
			</div>
		</div>
		<div class="col-6 col-paral">
			<a href="http://itworks-epitech.herokuapp.com/users/new"><img alt="Search" border="0" 
			src="https://res.cloudinary.com/dfefpyzcm/image/upload/v1643994911/pexels-andrea-piacquadio-3761509_im4k2h.png", class="img-fluid img-index-bloc"/></a> 


			<div class="bloc-bleu">
				<a href="http://itworks-epitech.herokuapp.com/users/new"><p class="bloc-bleu-text">Dons</p></a>
			</div>
		</div>
	</div>
</div>

<div class="container-fluid">
	<div class="paral-index"></div>
</div>

<div class="container">
	<p class="home-title-text">"Soutenir ma candidature, c'est rejoindre un mouvement."</p>
</div>

app/views/layouts/_footer.html.erb
<div class="footer-all">
    <div style="height:30px;"></div>    
    <div class="container-fluid footer-text-color">
       <div class="row justify-content-md-center">
        <div class="col-4 sm-12">
           <%= image_tag "https://res.cloudinary.com/dfefpyzcm/image/upload/v1643906541/cora-technology_yev2of.png", alt:"intro", class:"img-fluid cora-tech-footer"%>
        </div>
      <div class="col-3 sm-12">
        <h3 class="footer_title">Avec vous</h3>
        <p><%= link_to 'La candidature', root_path, class:'footer_item' %></p>
         <p><%= link_to 'Les soutiens', posts_path, class:'footer_item' %></p>
        <p><%= link_to "Je témoigne", new_post_path, class:'footer_item' %></p>
      </div>
      <div class="col-4 sm-12 col-temoignage">
        <h3 class="footer_title">Je soutiens Cora</h3>   
        <p>Ensemble nous pouvons changer le cours d'Epitech ! </br>Partagez vos témoignages sur notre plateforme ou écrivez-nous directement à l'adresse contact@coraforepitech.com</p>
      </div>  
    <div class="row">   
  </div>
  <div style="height:70px;"></div> 
</div>

<div class="footer_2">  
    <div class="container-fluid footer-text-color">
       <div class="row justify-content-md-center">
        <div class="col-6 sm-12">
        <p>© 2022 Cora Technology™. All Rights Reserved 
      </div>
       <div class="col-6 sm-12 payment-footer">
         <%= image_tag "https://res.cloudinary.com/dfefpyzcm/image/upload/v1643909367/payment-options_xsalnd.png", alt:"intro", class:"img-fluid"%>
      </div>  
    <div class="row">   
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header>
	<div class='container-fluid navbar-background fixed-top'>
		<div class="row">
			<div class="col-1 connexion-menu">
				<%= image_tag "https://res.cloudinary.com/dfefpyzcm/image/upload/v1643911463/mini-logo_eqzukr.png", alt:"intro", class:"logo-nav menu_item"%>
			</div>
			<div class="col-2 menu_item">
				<%= link_to 'LA CANDIDATURE', root_path, class:'menu_text'%>
			</div>
			<div class="col-2 menu_item menu_item2">
				<%= link_to 'LES SOUTIENS', posts_path, class:'menu_text' %>
			</div>

			<div class="col-3 menu_item">
				<%= link_to 'JE TEMOIGNE', new_post_path, class:'menu_text' %>
			</div>


			<div class="col-4 connexion-navigation">
				<% if user_signed_in? %>
				<%= link_to current_user.email, user_path(current_user), class:'menu_item menu-nav' %>
				<%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class:'menu_item' %>
				<% else %>
				<%= link_to 'Connexion', new_user_session_path, class:'menu_item' %>
				<%= link_to 'Inscription', new_user_registration_path, class:'menu_item' %>
				<% end %>
			</div>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/navigation' %>
      <div style="height:50px">
      </div>
      <%= yield %>
     <div style="height:50px;"></div>
     <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local:true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
<div class="container">
  <div class="bloc-title-form">
    <h1 class="title-form">Je soutiens Cora</h1>
  </div>
  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  
  <div class="actions">
    <%= form.submit "Poster mon témoignage", class:'margin-right'%>
    <%=link_to "Voir tous les témoignages", posts_path, class:'btn btn-custom btn-custom2' %>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="container">
    
    <div class="row row-title">
      <div class="col">
        <p>
          <strong>Sujet :</strong>
          <%= post.title %>
        </p>
      </div>
    </div>
    <div class="row row-content">
      <div class="col">
        <p>
          <%= post.content %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div style="height:30px;"></div>
<%= render "form", post: @post %>


<div style="height:50px;"></div>
<div class="paral"></div>
<div style="margin-bottom:-100px;"></div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid banner-top-posts"> 
  <div class="row">
    <div class="col-6">
      <%= image_tag "https://res.cloudinary.com/dfefpyzcm/image/upload/v1643897754/soutien_mfs2nm.jpg", alt:"intro", class:"img-fluid"%>  
    </div>
    <div class="col-6">
      <h1 class="title-banner-top-posts">Rejoignez la communauté</h1>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
    </div>
  </div>
</div>

<div style="height:50px;"></div>

<div class="container"> 
  <div class="row">
    <div class="col-6 col-padding-right">
       <h1 class="title-banner-top-posts2">Vous souhaitez rejoindre le mouvement et soutenir Cora ? N'hésitez plus ! Vous pouvez désormais publier votre témoignage sur notre plateforme.</h1>
    </div>
    <div class="col-4 banner-top-posts3">
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
      <div style="height:10px"></div>
      <p><%= link_to "Je rejoins la communauté", new_user_registration_path,class:'btn btn-secondary btn-custom' %></p>
    </div>
  </div>
</div>

<div style="height:30px;"></div>


<div class="container">
  <div class="row">
    <div class="col-12">
        <% @posts.each do |post|%>
          <div class="post-col">
            <%= render post %>
              <div class="bottom-post">
                <p>
                  <%= link_to "Consulter", post, class:'btn btn-secondary'%>
                  <% if post.user == current_user %>
                    <%= link_to 'Modifier', edit_post_path(post),  class:'btn btn-secondary' %>
                    <%= link_to 'Supprimer', post, method: :delete, data: { confirm: 'Etes vous sur de ne plus soutenir Cora ? Ceci est une grave erreur'},  class:'btn btn-secondary'; %>
                  <% end %>
                </p>
              </div>
            </div>
            <% end %>
          </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div style="height:50px;"></div>
<div class="container">
  <div class="row">
    <div class="col-6">
      <h1 class="title-new_post">Je témoigne</h1>
    </div>
    <div class="col-4 border-left-title">
      <p class="welcome2">Ensemble,</p>
      <p class="welcome2">nous pouvons</p>
      <p class="welcome2">intégrer Epitech</p>
    </div>
  </div>
</div>
<div class="container-fluid bg-new-post">
  <div class="container">
    <div class="row">
      <div class="col-4">
        <%= image_tag "https://res.cloudinary.com/dfefpyzcm/image/upload/v1643982476/cfe1_jf0zqs.png", alt:"intro", class:"img-fluid test"%>  
      </div>
      <div class="col-4">
        <%= image_tag "https://res.cloudinary.com/dfefpyzcm/image/upload/v1643982482/cfe2_r5fzpp.png", alt:"intro", class:"img-fluid"%>  
      </div>
      <div class="col-4">
        <%= image_tag "https://res.cloudinary.com/dfefpyzcm/image/upload/v1643982487/cfe3_bgruxi.png", alt:"intro", class:"img-fluid"%>  
      </div>

    </div>
  </div>
</div>

<div class="container">
    <%= render "form", post: @post %>
    <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
<div style="height:50px;"></div>
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div class="row border-show-post">
  <div class="col-6">
   <%= link_to "Modifier mon témoignage", edit_post_path(@post), class:'left-show-post btn btn-custom' %>
  <%= link_to "Voir tous les témoignages", posts_path, class:'left-show-post btn btn-custom' %>
</div>
<div class="col-6 col-align-right">
  <%= button_to "Ne plus soutenir Cora", @post, method: :delete ,class:'right-show-post btn btn-custom'%>
</div>
</div>
</div>
</div>
<div style="height:50px;"></div>
<div class="paral"></div>
   </div>
</div>
<div style="margin-bottom:-100px;"></div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container-fluid margin-b">
	<video id="background-video" autoplay loop muted>
		<source src="https://res.cloudinary.com/dfefpyzcm/video/upload/v1644251106/pexels-cottonbro-5912047_zqil9g.mp4">
	</video>

	<div class="content">
    		<a href="https://www.coinbase.com/signin?return_to=%2Fdashboard"><img alt="Search" border="0" 
    		src="https://res.cloudinary.com/dfefpyzcm/image/upload/v1644255953/bit_httom3.png" class="coinbase"></a> 
    	  	<p><span style="font-weight: 700">Adresse : </span><span id="tocopy">3PboAB9kY944w55omL6Joo5NK9giGeUSBr/</span></p>
    	   	<p><input type="button" value="Copier" class="js-copy btn-custom" 	data-target="#tocopy">
    		</p>
	</div>
</div>

<script>
	var btncopy = document.querySelector('.js-copy');
if(btncopy) {
    btncopy.addEventListener('click', docopy);
}

function docopy() {

    // Cible de l'élément qui doit être copié
    var target = this.dataset.target;
    var fromElement = document.querySelector(target);
    if(!fromElement) return;

    // Sélection des caractères concernés
    var range = document.createRange();
    var selection = window.getSelection();
    range.selectNode(fromElement);
    selection.removeAllRanges();
    selection.addRange(range);

    try {
        // Exécution de la commande de copie
        var result = document.execCommand('copy');
        if (result) {
            // La copie a réussi
            alert('Copié !');
        }
    }
    catch(err) {
        // Une erreur est surevnue lors de la tentative de copie
        alert(err);
    }

    // Fin de l'opération
    selection = window.getSelection();
    if (typeof selection.removeRange === 'function') {
        selection.removeRange(range);
    } else if (typeof selection.removeAllRanges === 'function') {
        selection.removeAllRanges();
    }
}
</script>

app/views/users/show.html.erb
<div style="height:50px;"></div>
<div class="container">
	<div class="row">
		<div class ="col-6">	
			<h1 class="welcome">Bienvenue !</h1>
		</div>
		<div class="col-4 border-left-title">
			<p class="welcome2">Témoignages</p>
			<p class="welcome2">soutien moral</p>
			<p class="welcome2">& financement</p>
		</div>
	</div>

	<div class="row">
		<div class="col-12">
			<%= image_tag "https://res.cloudinary.com/dfefpyzcm/image/upload/v1643965557/la-secte_fz2lwu.png", alt:"intro", class:"img-fluid"%>
		</div>
	</div>

	<div class="row border-slider">
		<div class="col-12">
			<h1 class="font-border-slider">Bienvenue, tu fais désormais partie de l'Association des amis de Cora ;)</h1>
		</div>
	</div>
	<div style="height:50px;"></div>
	<div class="row">
		<div class="col-12">
			<div class="title-bottom-user1">Mon adresse : <%= @user.email %> </div>
			<div class="title-bottom-user2">Mes témoignages </div>
			<div class="title-bottom-user3">	<% @posts.each do |post| %>
					<p><%= link_to post.title, post_path(post) %></p>
					<p><%= link_to post.content, post_path(post) %></p>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>